[package]
edition = "2021"
name = "affect-storage-mocks"
version = "0.1.0"

[dependencies]
affect-storage = { path = "../" }
async-trait = "0.1"
mockall = "0.11"
uuid = { version = "0.8", features = ["v4"] }
